### ISSUE TITLE
Bugzilla server now using untrusted SSL certificate

### ISSUE THREAD

**Issue by light-pedals** [frasertweedale/bugzillatools#18]
Just discovered that the system admin added an untrusted SSL certificate.  My bugzillatools script is failing.  Any suggestions on how to fix.

> $ bugzilla info 58478
> Bug 58478:
> Traceback (most recent call last):
>   File "/usr/local/bin/bugzilla", line 83, in <module>
>     args.command(args, parser, commands, aliases, ui)()
>   File "/usr/local/lib/python2.7/dist-packages/bzlib/command.py", line 535, in **call**
>     fields = config.show_fields & bug.data.viewkeys()
>   File "/usr/local/lib/python2.7/dist-packages/bzlib/bug.py", line 30, in data
>     self._data = self.rpc('get', ids=[self.bugno])['bugs'][0]
>   File "/usr/local/lib/python2.7/dist-packages/bzlib/bug.py", line 144, in rpc
>     return self.bz.rpc(_(('Bug',) + args), *_kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/bzlib/bugzilla.py", line 138, in rpc
>     return method(kwargs)
>   File "/usr/lib/python2.7/xmlrpclib.py", line 1240, in __call__
>     return self.**send(self.__name, args)
>   File "/usr/lib/python2.7/xmlrpclib.py", line 1599, in __request
>     verbose=self.__verbose
>   File "/usr/lib/python2.7/xmlrpclib.py", line 1280, in request
>     return self.single_request(host, handler, request_body, verbose)
>   File "/usr/lib/python2.7/xmlrpclib.py", line 1308, in single_request
>     self.send_content(h, request_body)
>   File "/usr/lib/python2.7/xmlrpclib.py", line 1456, in send_content
>     connection.endheaders(request_body)
>   File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
>     self._send_output(message_body)
>   File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
>     self.send(msg)
>   File "/usr/lib/python2.7/httplib.py", line 859, in send
>     self.connect()
>   File "/usr/lib/python2.7/httplib.py", line 1278, in connect
>     server_hostname=server_hostname)
>   File "/usr/lib/python2.7/ssl.py", line 352, in wrap_socket
>     _context=self)
>   File "/usr/lib/python2.7/ssl.py", line 597, in __init**
>     self.do_handshake()
>   File "/usr/lib/python2.7/ssl.py", line 826, in do_handshake
>     self._sslobj.do_handshake()
> ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

**Comment by light-pedals** [comment]
Thanks a co-worker Steve who researched other site, I have a work around.  

Requires modification of xmlrpclib.py

import xmlrpclib
Import ssl  # Add Line
.
.
.
self.server = xmlrpclib.ServerProxy(
            str(url),
            use_datetime=True,
            Allow_none=True,. # Add Comma
           context=ssl._create_unverified_context()    # Add Line
)

Reference stackoverflow article that describes workaround.   

http://stackoverflow.com/questions/30461969/disable-default-certificate-verification-in-python-2-7-9
